version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 292002
      POSTGRES_DB: postgres
    networks:
      - chat-app-network

  chat-app:
    build: .
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 292002
      DB_NAME: postgres
      DB_PORT: 5432
      DB_SSLMODE: disable
    depends_on:
      - db
    networks:
      - chat-app-network

networks:
  chat-app-network:
    driver: bridge
